#!/bin/bash
# test-colors.sh
echo "This is the default prompt"
PS1="\e[01;31m"
echo -e "${PS1}This prompt is in red"
PS1="\e[01;32m"
echo -e "${PS1}This prompt is in green"
PS1="\e[01;33m"
echo -e "${PS1}This prompt is in yellow"
PS1="\e[01;34m"
echo -e "${PS1}This prompt is in blue"
PS1="\e[01;35m"
echo -e "${PS1}This prompt is in purple"
PS1="\e[01;36m"
echo -e "${PS1}This prompt is in cian"
PS1="\e[01;37m"
echo -e "${PS1}This prompt is in white"
#PS1="\e[0;29m"
#echo -e "${PS1}This prompt is back to the default"
